# Generated by Django 4.0.4 on 2024-01-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encodeX', '0005_usercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
