# Generated by Django 4.0.4 on 2024-01-03 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encodeX', '0006_usercode_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='encodedimage',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='encodedimage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encodedimage',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
