# Generated by Django 4.0.4 on 2024-01-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encodeX', '0007_encodedimage_date_time_encodedimage_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encodedimage',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercode',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
